services:
  - type: web
    name: studyvibe-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: APP_NAME
        sync: false
      - key: API_VERSION
        value: v1
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
